glossary: dict = {
    "Computer": "Computer is an electronic device that takes an input, processes it and then generates it output.",
    "Input": "Anything taken from a user.",
    "Processing": "All the logical and arithmetic operations performed on the input to generate output.",
    "Output": "Anything generated by the computer.",
    "Data": "A collection of raw facts and figures.",
}

print(f"Computer : {glossary["Computer"]}")
print(f"Input : {glossary["Input"]}")
print(f"Processing : {glossary["Processing"]}")
print(f"Output : {glossary["Output"]}")
print(f"Data : {glossary["Data"]}")
