glossary: dict = {
    "Computer": "Computer is an electronic device that takes an input, processes it and then generates it output.",
    "Input": "Anything taken from a user.",
    "Processing": "All the logical and arithmetic operations performed on the input to generate output.",
    "Ouput": "Anything generated by the computer.",
    "Data": "A collection of raw facts and figures.",
    "Computer": "Computer is an electronic device that takes an input, processes it and then generates it output.",
    "Input": "Anything taken from a user.",
    "Processing": "All the logical and arithmetic operations performed on the input to generate output.",
    "Ouput": "Anything generated by the computer.",
    "Data": "A collection of raw facts and figures.",
}

for key, value in glossary.items():
    print(f"{key} : {value}")
