places:list[str] = ["Hong Kong","China","London","Turkey","Saudi Arabia"]
print(f"Original Order : {places}")
print(f"Sorted Order : {sorted(places)}")
print(f"Still in Original Order : {places}")
print(f"Reverse of Sorted Order List : {sorted(places,reverse=True)}")
print(f"Still in Original Order : {places}")
places.reverse()
print(f"Reversed Order : {places}")
places.reverse()
print(f"Reversed Order : {places}")
places.sort()
print(f"Sort Order : {places}")
places.sort()
print(f"Reverse of Sort Order : {places}")